// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Swagger.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CustomerCustomerDemo
    {
        /// <summary>
        /// Initializes a new instance of the CustomerCustomerDemo class.
        /// </summary>
        public CustomerCustomerDemo()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CustomerCustomerDemo class.
        /// </summary>
        public CustomerCustomerDemo(string customerId = default(string), string customerTypeId = default(string), Customers customer = default(Customers), CustomerDemographics customerType = default(CustomerDemographics))
        {
            CustomerId = customerId;
            CustomerTypeId = customerTypeId;
            Customer = customer;
            CustomerType = customerType;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CustomerId")]
        public string CustomerId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CustomerTypeId")]
        public string CustomerTypeId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Customer")]
        public Customers Customer { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CustomerType")]
        public CustomerDemographics CustomerType { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (CustomerId != null)
            {
                if (CustomerId.Length > 5)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "CustomerId", 5);
                }
                if (CustomerId.Length < 0)
                {
                    throw new ValidationException(ValidationRules.MinLength, "CustomerId", 0);
                }
            }
            if (CustomerTypeId != null)
            {
                if (CustomerTypeId.Length > 10)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "CustomerTypeId", 10);
                }
                if (CustomerTypeId.Length < 0)
                {
                    throw new ValidationException(ValidationRules.MinLength, "CustomerTypeId", 0);
                }
            }
            if (Customer != null)
            {
                Customer.Validate();
            }
            if (CustomerType != null)
            {
                CustomerType.Validate();
            }
        }
    }
}
