// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Swagger.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Products
    {
        /// <summary>
        /// Initializes a new instance of the Products class.
        /// </summary>
        public Products()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Products class.
        /// </summary>
        public Products(string productName, int? productId = default(int?), int? supplierId = default(int?), int? categoryId = default(int?), string quantityPerUnit = default(string), double? unitPrice = default(double?), int? unitsInStock = default(int?), int? unitsOnOrder = default(int?), int? reorderLevel = default(int?), bool? discontinued = default(bool?), Categories category = default(Categories), Suppliers supplier = default(Suppliers), IList<OrderDetails> orderDetails = default(IList<OrderDetails>))
        {
            ProductId = productId;
            ProductName = productName;
            SupplierId = supplierId;
            CategoryId = categoryId;
            QuantityPerUnit = quantityPerUnit;
            UnitPrice = unitPrice;
            UnitsInStock = unitsInStock;
            UnitsOnOrder = unitsOnOrder;
            ReorderLevel = reorderLevel;
            Discontinued = discontinued;
            Category = category;
            Supplier = supplier;
            OrderDetails = orderDetails;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ProductId")]
        public int? ProductId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ProductName")]
        public string ProductName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SupplierId")]
        public int? SupplierId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CategoryId")]
        public int? CategoryId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "QuantityPerUnit")]
        public string QuantityPerUnit { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "UnitPrice")]
        public double? UnitPrice { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "UnitsInStock")]
        public int? UnitsInStock { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "UnitsOnOrder")]
        public int? UnitsOnOrder { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ReorderLevel")]
        public int? ReorderLevel { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Discontinued")]
        public bool? Discontinued { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Category")]
        public Categories Category { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Supplier")]
        public Suppliers Supplier { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "OrderDetails")]
        public IList<OrderDetails> OrderDetails { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (ProductName == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "ProductName");
            }
            if (ProductName != null)
            {
                if (ProductName.Length > 40)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "ProductName", 40);
                }
                if (ProductName.Length < 0)
                {
                    throw new ValidationException(ValidationRules.MinLength, "ProductName", 0);
                }
            }
            if (QuantityPerUnit != null)
            {
                if (QuantityPerUnit.Length > 20)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "QuantityPerUnit", 20);
                }
                if (QuantityPerUnit.Length < 0)
                {
                    throw new ValidationException(ValidationRules.MinLength, "QuantityPerUnit", 0);
                }
            }
            if (Category != null)
            {
                Category.Validate();
            }
            if (Supplier != null)
            {
                Supplier.Validate();
            }
            if (OrderDetails != null)
            {
                foreach (var element in OrderDetails)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
    }
}
